### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [ofajardo/pyreadr_wheels3#1]
Problem
---------
On aarch64, ‘pip install pyreadr’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install pyreadr’ should download the wheels from pypi.

@ofajardo and Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by ofajardo** [comment]
thanks for the contribution! 
Somehow tests are failing now with a very strange error message. I assume that it is unrelated to these changes ... but it was working before ... have you seen those errors as well?

**Comment by odidev** [comment]
> have you seen those errors as well?

In my forked repo as well, these errors were seen even before the changes so it's not related to these changes.

**Comment by ofajardo** [comment]
OK solved and new version pushed with the new arch wheels on pypi
